"""Strict external-evidence attestation for still-generic maturity proof routes.

This module fills an infrastructure gap only: the proof policy already defines
capability-specific external acceptance routes, but many of those routes had no
repo-backed validator that could safely consume a real external observation.

Security / honesty boundaries:
- Only generic external routes generated by the committed policy are accepted.
  Specialized routes (for example sim-to-reality or post-deployment) are NOT
  accepted here and must keep using their dedicated semantic attestors.
- The exact capability, proof kind, subject, verifier and reference namespace are
  derived from the committed effective policy for the clean Git revision.
- External evidence must carry a separate verifier-key HMAC signature. The
  verifier key is never stored in the repository, receipt or proof ledger.
- The proof-ledger integrity key is a different trust root and is also external.
- Proof-kind-specific schemas are recomputed/validated; a generic ``passed=true``
  blob is never enough.
- This code never auto-generates evidence, never calls hardware/live systems and
  never says the underlying scientific claim is true. It only records a signed,
  bounded external observation when a trusted verifier actually supplies one.
"""
from __future__ import annotations

import base64
import hashlib
import hmac
import json
import math
import os
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Any, Dict, Mapping, Optional, Sequence, Tuple

from utils.release_identity import repository_identity

from .capability_registry import CAPABILITY_BY_ID, ProofKind
from .maturity_auditor import (
    TrustedMaturityAudit,
    _parse_policy,
    _read_policy_bytes,
    _tracked_index,
    audit_repository_maturity,
)
from .maturity_proof import ProofLedger


_SCHEMA_VERSION = 1
_MAX_RECEIPT_BYTES = 2 * 1024 * 1024
_MAX_RECEIPT_AGE_SECONDS = 6 * 60 * 60
_MAX_FUTURE_SKEW_SECONDS = 5 * 60
_MAX_VALIDITY_SECONDS = 24 * 60 * 60
_SHA_RE = re.compile(r"^[0-9a-f]{64}$")
_GIT_SHA_RE = re.compile(r"^[0-9a-f]{40}$")
_SAFE_ID_RE = re.compile(r"^[A-Za-z0-9_.:@/+~-]{1,200}$")
_B64URL_RE = re.compile(r"^[A-Za-z0-9_-]+$")
_SIGNATURE_DOMAIN = b"rv-ai-external-proof-v1\x00"

_GENERIC_ROUTE = {
    ProofKind.EXECUTION: (
        "trusted-execution-attestor", "execution-run", "execution"
    ),
    ProofKind.REPRODUCIBILITY: (
        "trusted-reproducibility-attestor", "reproducibility-run", "reproducibility"
    ),
    ProofKind.INDEPENDENT: (
        "trusted-independent-validator", "independent-validation", "independent"
    ),
    ProofKind.PERSISTENCE: (
        "trusted-persistence-attestor", "persistence-observation", "persistence"
    ),
    ProofKind.RUNTIME: (
        "trusted-runtime-attestor", "runtime-observation", "runtime"
    ),
    ProofKind.LIVE: (
        "trusted-live-observer", "live-observation", "live"
    ),
    ProofKind.HARDWARE: (
        "trusted-hardware-lab", "hardware-observation", "hardware"
    ),
    ProofKind.SAFETY: (
        "trusted-safety-officer", "safety-gate", "safety"
    ),
}


def _canonical(value: Any) -> bytes:
    return json.dumps(
        value,
        ensure_ascii=False,
        sort_keys=True,
        separators=(",", ":"),
        allow_nan=False,
    ).encode("utf-8")


def _sha(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def _safe_sha(value: object, field: str) -> str:
    text = str(value or "").strip().lower()
    if not _SHA_RE.fullmatch(text):
        raise ValueError(f"{field} must be a SHA-256 hex digest")
    return text


def _safe_id(value: object, field: str) -> str:
    text = str(value or "").strip()
    if not _SAFE_ID_RE.fullmatch(text):
        raise ValueError(f"{field} is invalid")
    return text


def _finite(value: object, field: str) -> float:
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise ValueError(f"{field} must be numeric")
    number = float(value)
    if not math.isfinite(number):
        raise ValueError(f"{field} must be finite")
    return number


def _positive_int(value: object, field: str, *, minimum: int = 1) -> int:
    if type(value) is not int or value < minimum:
        raise ValueError(f"{field} must be an integer >= {minimum}")
    return int(value)


def _b64(data: bytes) -> str:
    return base64.urlsafe_b64encode(data).rstrip(b"=").decode("ascii")


def _unb64(text: object) -> bytes:
    raw = str(text or "")
    if not raw or not _B64URL_RE.fullmatch(raw):
        raise ValueError("signature is not canonical base64url")
    padding = "=" * ((4 - len(raw) % 4) % 4)
    try:
        decoded = base64.urlsafe_b64decode((raw + padding).encode("ascii"))
    except Exception as exc:
        raise ValueError("signature is not valid base64url") from exc
    if not hmac.compare_digest(_b64(decoded), raw):
        raise ValueError("signature uses non-canonical base64url")
    return decoded


def _require_key(value: bytes | bytearray, field: str) -> bytes:
    if not isinstance(value, (bytes, bytearray)) or len(value) < 32:
        raise ValueError(f"{field} must be at least 32 bytes")
    return bytes(value)


def sign_external_receipt(unsigned_receipt: Mapping[str, Any], *, verifier_key: bytes) -> str:
    """Return a canonical HMAC signature for a receipt payload without signature.

    This helper is intended for a protected trusted-verifier environment. It is
    deterministic so independent tooling can reproduce the signature check.
    """
    key = _require_key(verifier_key, "verifier_key")
    if not isinstance(unsigned_receipt, Mapping) or "signature" in unsigned_receipt:
        raise ValueError("unsigned_receipt must be a mapping without signature")
    return _b64(hmac.new(key, _SIGNATURE_DOMAIN + _canonical(unsigned_receipt), hashlib.sha256).digest())


def _read_bounded_json(path: Path) -> tuple[Mapping[str, Any], bytes]:
    try:
        info = path.stat()
    except OSError as exc:
        raise ValueError("external proof receipt cannot be read") from exc
    if not path.is_file() or info.st_size < 1 or info.st_size > _MAX_RECEIPT_BYTES:
        raise ValueError("external proof receipt size is invalid")
    data = path.read_bytes()
    if len(data) != info.st_size or len(data) > _MAX_RECEIPT_BYTES:
        raise ValueError("external proof receipt changed during read")
    try:
        value = json.loads(data.decode("utf-8"))
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise ValueError("external proof receipt is not valid UTF-8 JSON") from exc
    if not isinstance(value, dict):
        raise ValueError("external proof receipt must be a JSON object")
    return value, data


def _validate_interval(start: object, finish: object, *, now: float, prefix: str) -> tuple[float, float]:
    started = _finite(start, f"{prefix}.started_at_epoch")
    finished = _finite(finish, f"{prefix}.finished_at_epoch")
    if started < 0 or finished < started:
        raise ValueError(f"{prefix} time interval is invalid")
    if finished > now + _MAX_FUTURE_SKEW_SECONDS:
        raise ValueError(f"{prefix} finishes in the future")
    return started, finished


def _validate_execution(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {
        "run_id", "started_at_epoch", "finished_at_epoch", "result_hash",
        "exit_code", "execution_complete", "truth_proven",
    }
    if set(evidence) != expected:
        raise ValueError("execution evidence schema is invalid")
    _safe_id(evidence["run_id"], "execution.run_id")
    _validate_interval(evidence["started_at_epoch"], evidence["finished_at_epoch"], now=now, prefix="execution")
    _safe_sha(evidence["result_hash"], "execution.result_hash")
    if type(evidence["exit_code"]) is not int or evidence["exit_code"] != 0:
        raise ValueError("execution exit_code must be zero")
    if evidence["execution_complete"] is not True:
        raise ValueError("execution is not complete")
    if evidence["truth_proven"] is not False:
        raise ValueError("execution evidence must not claim truth_proven")
    return None


def _validate_reproducibility(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {"runs", "comparison_hash", "reproducibility_confirmed", "truth_proven"}
    if set(evidence) != expected:
        raise ValueError("reproducibility evidence schema is invalid")
    runs = evidence["runs"]
    if not isinstance(runs, list) or not (2 <= len(runs) <= 50):
        raise ValueError("reproducibility requires 2..50 bounded repeat runs")
    ids = set()
    hashes = []
    for index, row in enumerate(runs):
        if not isinstance(row, dict) or set(row) != {
            "run_id", "started_at_epoch", "finished_at_epoch", "result_hash"
        }:
            raise ValueError(f"reproducibility run {index} schema is invalid")
        run_id = _safe_id(row["run_id"], f"reproducibility.runs[{index}].run_id")
        if run_id in ids:
            raise ValueError("reproducibility run_id values must be distinct")
        ids.add(run_id)
        _validate_interval(row["started_at_epoch"], row["finished_at_epoch"], now=now, prefix=f"reproducibility.runs[{index}]")
        hashes.append(_safe_sha(row["result_hash"], f"reproducibility.runs[{index}].result_hash"))
    _safe_sha(evidence["comparison_hash"], "reproducibility.comparison_hash")
    if evidence["reproducibility_confirmed"] is not True:
        raise ValueError("reproducibility comparison is not confirmed")
    if evidence["truth_proven"] is not False:
        raise ValueError("reproducibility evidence must not claim truth_proven")
    # Identical hashes are allowed but not required: stochastic algorithms may
    # legitimately differ while a signed comparison artifact verifies tolerance.
    return None


def _validate_independent(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {
        "validation_id", "validator_id", "implementation_actor_id",
        "validator_environment_id", "implementation_environment_id",
        "result_hash", "independent_validation_complete", "truth_proven",
    }
    if set(evidence) != expected:
        raise ValueError("independent-validation evidence schema is invalid")
    _safe_id(evidence["validation_id"], "independent.validation_id")
    validator = _safe_id(evidence["validator_id"], "independent.validator_id")
    actor = _safe_id(evidence["implementation_actor_id"], "independent.implementation_actor_id")
    validator_env = _safe_id(evidence["validator_environment_id"], "independent.validator_environment_id")
    implementation_env = _safe_id(evidence["implementation_environment_id"], "independent.implementation_environment_id")
    if hmac.compare_digest(validator, actor):
        raise ValueError("independent validator must differ from implementation actor")
    if hmac.compare_digest(validator_env, implementation_env):
        raise ValueError("independent validation environment must differ from implementation environment")
    _safe_sha(evidence["result_hash"], "independent.result_hash")
    if evidence["independent_validation_complete"] is not True:
        raise ValueError("independent validation is incomplete")
    if evidence["truth_proven"] is not False:
        raise ValueError("independent validation must not claim truth_proven")
    return None


def _validate_persistence(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {"checkpoints", "persistence_confirmed", "truth_proven"}
    if set(evidence) != expected:
        raise ValueError("persistence evidence schema is invalid")
    checkpoints = evidence["checkpoints"]
    if not isinstance(checkpoints, list) or not (2 <= len(checkpoints) <= 100):
        raise ValueError("persistence requires 2..100 checkpoints")
    ids = set()
    previous = -1.0
    for index, row in enumerate(checkpoints):
        if not isinstance(row, dict) or set(row) != {
            "checkpoint_id", "observed_at_epoch", "state_hash", "reload_verified"
        }:
            raise ValueError(f"persistence checkpoint {index} schema is invalid")
        checkpoint_id = _safe_id(row["checkpoint_id"], f"persistence.checkpoints[{index}].checkpoint_id")
        if checkpoint_id in ids:
            raise ValueError("persistence checkpoint IDs must be distinct")
        ids.add(checkpoint_id)
        observed = _finite(row["observed_at_epoch"], f"persistence.checkpoints[{index}].observed_at_epoch")
        if observed <= previous or observed > now + _MAX_FUTURE_SKEW_SECONDS:
            raise ValueError("persistence checkpoint times must strictly increase and not be future")
        previous = observed
        _safe_sha(row["state_hash"], f"persistence.checkpoints[{index}].state_hash")
        if row["reload_verified"] is not True:
            raise ValueError("every persistence checkpoint must pass reload verification")
    if evidence["persistence_confirmed"] is not True:
        raise ValueError("persistence is not confirmed")
    if evidence["truth_proven"] is not False:
        raise ValueError("persistence evidence must not claim truth_proven")
    return None


def _validate_runtime_like(
    evidence: Mapping[str, Any], *, now: float, live: bool
) -> Optional[float]:
    base = {
        "run_id", "started_at_epoch", "finished_at_epoch", "duration_seconds",
        "environment_id", "observations_count", "result_hash", "valid_until_epoch",
        "truth_proven",
    }
    expected = set(base)
    expected.add("live_observed" if live else "runtime_observed")
    if live:
        expected.update({"external_target_id", "real_external_observation"})
    label = "live" if live else "runtime"
    if set(evidence) != expected:
        raise ValueError(f"{label} evidence schema is invalid")
    _safe_id(evidence["run_id"], f"{label}.run_id")
    started, finished = _validate_interval(
        evidence["started_at_epoch"], evidence["finished_at_epoch"], now=now, prefix=label
    )
    duration = _finite(evidence["duration_seconds"], f"{label}.duration_seconds")
    if duration <= 0 or not math.isclose(duration, finished - started, rel_tol=1e-9, abs_tol=1e-6):
        raise ValueError(f"{label} duration_seconds is inconsistent")
    _safe_id(evidence["environment_id"], f"{label}.environment_id")
    minimum_observations = 2 if live else 1
    _positive_int(evidence["observations_count"], f"{label}.observations_count", minimum=minimum_observations)
    _safe_sha(evidence["result_hash"], f"{label}.result_hash")
    flag = "live_observed" if live else "runtime_observed"
    if evidence[flag] is not True:
        raise ValueError(f"{label} observation is not confirmed")
    if live:
        _safe_id(evidence["external_target_id"], "live.external_target_id")
        if evidence["real_external_observation"] is not True:
            raise ValueError("live evidence must represent a real external observation")
    if evidence["truth_proven"] is not False:
        raise ValueError(f"{label} evidence must not claim truth_proven")
    valid_until = _finite(evidence["valid_until_epoch"], f"{label}.valid_until_epoch")
    if valid_until <= now or valid_until <= finished:
        raise ValueError(f"{label} valid_until_epoch must be in the future")
    if valid_until - now > _MAX_VALIDITY_SECONDS:
        raise ValueError(f"{label} evidence validity window is too long")
    return valid_until


def _validate_hardware(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {
        "observation_id", "device_id", "calibration_hash", "safety_approval_hash",
        "observations_count", "result_hash", "hardware_observed", "truth_proven",
    }
    if set(evidence) != expected:
        raise ValueError("hardware evidence schema is invalid")
    _safe_id(evidence["observation_id"], "hardware.observation_id")
    _safe_id(evidence["device_id"], "hardware.device_id")
    _safe_sha(evidence["calibration_hash"], "hardware.calibration_hash")
    _safe_sha(evidence["safety_approval_hash"], "hardware.safety_approval_hash")
    _positive_int(evidence["observations_count"], "hardware.observations_count")
    _safe_sha(evidence["result_hash"], "hardware.result_hash")
    if evidence["hardware_observed"] is not True:
        raise ValueError("hardware observation is not confirmed")
    if evidence["truth_proven"] is not False:
        raise ValueError("hardware observation must not claim truth_proven")
    return None


def _validate_safety(evidence: Mapping[str, Any], *, now: float) -> Optional[float]:
    expected = {
        "safety_case_hash", "hazards_count", "tests_executed", "tests_passed",
        "unresolved_critical_hazards", "result_hash", "safety_gate_passed",
        "truth_proven",
    }
    if set(evidence) != expected:
        raise ValueError("safety evidence schema is invalid")
    _safe_sha(evidence["safety_case_hash"], "safety.safety_case_hash")
    _positive_int(evidence["hazards_count"], "safety.hazards_count")
    executed = _positive_int(evidence["tests_executed"], "safety.tests_executed")
    passed = _positive_int(evidence["tests_passed"], "safety.tests_passed")
    if passed != executed:
        raise ValueError("all executed safety tests must pass")
    if type(evidence["unresolved_critical_hazards"]) is not int or evidence["unresolved_critical_hazards"] != 0:
        raise ValueError("unresolved critical safety hazards must be zero")
    _safe_sha(evidence["result_hash"], "safety.result_hash")
    if evidence["safety_gate_passed"] is not True:
        raise ValueError("safety gate is not confirmed")
    if evidence["truth_proven"] is not False:
        raise ValueError("safety evidence must not claim truth_proven")
    return None


_VALIDATORS = {
    ProofKind.EXECUTION: _validate_execution,
    ProofKind.REPRODUCIBILITY: _validate_reproducibility,
    ProofKind.INDEPENDENT: _validate_independent,
    ProofKind.PERSISTENCE: _validate_persistence,
    ProofKind.RUNTIME: lambda evidence, now: _validate_runtime_like(evidence, now=now, live=False),
    ProofKind.LIVE: lambda evidence, now: _validate_runtime_like(evidence, now=now, live=True),
    ProofKind.HARDWARE: _validate_hardware,
    ProofKind.SAFETY: _validate_safety,
}


@dataclass(frozen=True)
class ExternalEvidenceReceipt:
    revision: str
    created_at_epoch: float
    capability_id: int
    proof_kind: ProofKind
    subject: str
    verifier: str
    reference: str
    protocol_hash: str
    evidence_hash: str
    receipt_sha256: str
    valid_until: Optional[float]


@dataclass(frozen=True)
class ExternalProofAttestation:
    revision: str
    capability_id: int
    proof_kind: ProofKind
    receipt_sha256: str
    receipts_added: int
    receipts_reused: int
    anchor_token: str
    audit: TrustedMaturityAudit


def validate_external_evidence_receipt(
    path: str | os.PathLike[str],
    *,
    repo_root: str | os.PathLike[str],
    expected_revision: str,
    verifier_key: bytes,
    now: float,
    policy_path: str = "config/maturity_proof_policy.json",
) -> ExternalEvidenceReceipt:
    current_time = float(now)
    if not math.isfinite(current_time):
        raise ValueError("now must be finite")
    key = _require_key(verifier_key, "verifier_key")
    revision = str(expected_revision or "").strip().lower()
    if not _GIT_SHA_RE.fullmatch(revision):
        raise ValueError("expected_revision must be a full lowercase Git SHA")

    root = Path(repo_root).resolve(strict=True)
    tracked = _tracked_index(root)
    policy = _parse_policy(_read_policy_bytes(root, tracked, policy_path))
    policy_by_route = {(rule.capability_id, rule.proof_kind): rule for rule in policy.rules}

    value, raw = _read_bounded_json(Path(path).expanduser().resolve())
    expected_top = {
        "schema_version", "created_at_epoch", "implementation_revision",
        "capability_id", "proof_kind", "subject", "verifier", "reference",
        "protocol_hash", "evidence", "evidence_hash", "signature",
    }
    if set(value) != expected_top:
        raise ValueError("external proof receipt top-level schema is invalid")
    if value["schema_version"] != _SCHEMA_VERSION:
        raise ValueError("unsupported external proof receipt schema_version")
    created = _finite(value["created_at_epoch"], "created_at_epoch")
    if created > current_time + _MAX_FUTURE_SKEW_SECONDS:
        raise ValueError("external proof receipt is from the future")
    if current_time - created > _MAX_RECEIPT_AGE_SECONDS:
        raise ValueError("external proof receipt is stale")
    if str(value["implementation_revision"] or "").strip().lower() != revision:
        raise ValueError("external proof receipt revision mismatch")
    capability_id = value["capability_id"]
    if type(capability_id) is not int or capability_id not in CAPABILITY_BY_ID:
        raise ValueError("external proof receipt capability_id is invalid")
    try:
        kind = ProofKind(value["proof_kind"])
    except ValueError as exc:
        raise ValueError("external proof receipt proof_kind is invalid") from exc
    if kind not in _GENERIC_ROUTE or kind not in CAPABILITY_BY_ID[capability_id].required_proofs:
        raise ValueError("proof kind is not eligible for generic external attestation")

    expected_verifier, suffix, namespace = _GENERIC_ROUTE[kind]
    expected_subject = f"capability-{capability_id}-{suffix}"
    expected_prefix = f"{namespace}:c{capability_id}:"
    subject = _safe_id(value["subject"], "subject")
    verifier = _safe_id(value["verifier"], "verifier")
    reference = str(value["reference"] or "").strip()
    if subject != expected_subject or verifier != expected_verifier:
        raise ValueError("receipt does not target the canonical generic route")
    if not reference.startswith(expected_prefix) or len(reference) > 2_000:
        raise ValueError("receipt reference namespace is invalid")

    rule = policy_by_route.get((capability_id, kind))
    if rule is None:
        raise ValueError("committed proof policy has no route for receipt")
    if tuple(rule.subjects) != (expected_subject,) or tuple(rule.verifiers) != (expected_verifier,):
        # A specialized override intentionally changes this shape/verifier. The
        # generic attestor must not bypass that dedicated semantic validator.
        raise ValueError("route is specialized or differs from canonical generic policy")
    if tuple(rule.reference_prefixes) != (expected_prefix,):
        raise ValueError("generic route reference prefix differs from committed policy")

    protocol_hash = _safe_sha(value["protocol_hash"], "protocol_hash")
    evidence = value["evidence"]
    if not isinstance(evidence, dict):
        raise ValueError("external proof evidence must be an object")
    evidence_hash = _safe_sha(value["evidence_hash"], "evidence_hash")
    if evidence_hash != _sha(_canonical(evidence)):
        raise ValueError("evidence_hash verification failed")
    valid_until = _VALIDATORS[kind](evidence, now=current_time)

    unsigned = dict(value)
    signature_text = unsigned.pop("signature")
    expected_signature = hmac.new(
        key, _SIGNATURE_DOMAIN + _canonical(unsigned), hashlib.sha256
    ).digest()
    signature = _unb64(signature_text)
    if not hmac.compare_digest(signature, expected_signature):
        raise ValueError("external proof receipt signature verification failed")

    return ExternalEvidenceReceipt(
        revision=revision,
        created_at_epoch=created,
        capability_id=capability_id,
        proof_kind=kind,
        subject=subject,
        verifier=verifier,
        reference=reference,
        protocol_hash=protocol_hash,
        evidence_hash=evidence_hash,
        receipt_sha256=_sha(raw),
        valid_until=valid_until,
    )


def _outside_repo(root: Path, target: Path) -> bool:
    try:
        target.resolve().relative_to(root.resolve())
        return False
    except ValueError:
        return True


def attest_external_proof(
    *,
    repo_root: str | os.PathLike[str],
    evidence_receipt_path: str | os.PathLike[str],
    ledger_path: str | os.PathLike[str],
    ledger_integrity_key: bytes,
    verifier_key: bytes,
    now: float,
    prior_anchor_token: str = "",
    prior_revision: str = "",
    policy_path: str = "config/maturity_proof_policy.json",
) -> ExternalProofAttestation:
    """Validate one signed generic external observation and mint one proof."""
    current_time = float(now)
    if not math.isfinite(current_time):
        raise ValueError("now must be finite")
    ledger_key = _require_key(ledger_integrity_key, "ledger_integrity_key")
    _require_key(verifier_key, "verifier_key")
    root = Path(repo_root).resolve(strict=True)
    if not root.is_dir():
        raise ValueError("repo_root must be a directory")
    ledger_target = Path(ledger_path).expanduser().resolve()
    receipt_target = Path(evidence_receipt_path).expanduser().resolve()
    if not _outside_repo(root, ledger_target):
        raise ValueError("proof ledger must live outside the audited repository")
    if not _outside_repo(root, receipt_target):
        raise ValueError("external evidence receipt must live outside the audited repository")

    identity_before = repository_identity(root)
    revision = str(identity_before.get("revision") or "").strip().lower()
    if not identity_before.get("available") or not identity_before.get("clean") or not _GIT_SHA_RE.fullmatch(revision):
        raise ValueError("external proof attestation requires a clean Git checkout")

    receipt = validate_external_evidence_receipt(
        receipt_target,
        repo_root=root,
        expected_revision=revision,
        verifier_key=verifier_key,
        now=current_time,
        policy_path=policy_path,
    )

    ledger_exists = ledger_target.exists() and ledger_target.stat().st_size > 0
    ledger = ProofLedger(str(ledger_target), integrity_key=ledger_key)
    if ledger_exists:
        prior = str(prior_revision or "").strip().lower()
        if not prior_anchor_token or not _GIT_SHA_RE.fullmatch(prior):
            raise ValueError("existing proof ledger requires prior trusted anchor and revision")
        if not ledger.verify_chain(anchor_token=prior_anchor_token, current_revision=prior):
            raise ValueError("existing proof ledger failed prior anchor continuity check")
    elif prior_anchor_token or prior_revision:
        raise ValueError("prior anchor/revision supplied for an empty proof ledger")

    receipt_id = (
        f"ext:{receipt.receipt_sha256[:16]}:c{receipt.capability_id}:"
        f"{receipt.proof_kind.value}"
    )
    existing = [
        row for row in ledger._events()  # noqa: SLF001 - attestation continuity audit
        if row.get("event_type") == "ADD" and row.get("receipt_id") == receipt_id
    ]
    reused = 0
    added = 0
    if existing:
        if len(existing) != 1:
            raise ValueError("duplicate deterministic external proof receipt_id")
        row = existing[0]
        expected = {
            "capability_id": receipt.capability_id,
            "proof_kind": receipt.proof_kind.value,
            "subject": receipt.subject,
            "subject_sha256": receipt.receipt_sha256,
            "verifier": receipt.verifier,
            "reference": receipt.reference,
            "implementation_revision": revision,
        }
        if any(row.get(key) != value for key, value in expected.items()):
            raise ValueError("deterministic external proof receipt_id collision")
        reused = 1
    else:
        ledger.add(
            receipt_id=receipt_id,
            capability_id=receipt.capability_id,
            proof_kind=receipt.proof_kind,
            subject=receipt.subject,
            subject_sha256=receipt.receipt_sha256,
            verifier=receipt.verifier,
            observed_at=receipt.created_at_epoch,
            valid_until=receipt.valid_until,
            reference=receipt.reference,
            implementation_revision=revision,
        )
        added = 1

    anchor = ledger.create_anchor(current_revision=revision, issued_at=current_time)
    audit = audit_repository_maturity(
        repo_root=root,
        ledger_path=ledger_target,
        integrity_key=ledger_key,
        anchor_token=anchor,
        now=current_time,
        policy_path=policy_path,
    )
    if not audit.audit_valid:
        raise ValueError("trusted maturity audit rejected external proof attestation")

    identity_after = repository_identity(root)
    if (
        not identity_after.get("available")
        or not identity_after.get("clean")
        or str(identity_after.get("revision") or "").strip().lower() != revision
    ):
        raise ValueError("repository changed during external proof attestation")

    return ExternalProofAttestation(
        revision=revision,
        capability_id=receipt.capability_id,
        proof_kind=receipt.proof_kind,
        receipt_sha256=receipt.receipt_sha256,
        receipts_added=added,
        receipts_reused=reused,
        anchor_token=anchor,
        audit=audit,
    )
